### ISSUE TITLE
请问怎么编辑属性，比如 id, assignee 等

### ISSUE THREAD

**Issue by ittianyu** [Blenta/intellij-bpmn-editor#1]

**Comment by Blenta** [comment]
这个BPMN编辑器不是针对任何其他BPMN引擎（如：Activity, Flowable, Camunda）设计的。所以这些属性是不能编辑的。所以可编辑的属性都是通过右键Popup菜单编辑的。

**Comment by Jaryli** [comment]
![image](https://user-images.githubusercontent.com/2117086/30572197-d3a78c30-9d1e-11e7-80b6-04a590d82cc9.png)
